###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mariadb:
        image: 'mariadb:10.10'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=wordpress
        ports:
            - '3306:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - '.:/var/www/html:rw'
        ports:
            - '80:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui
    cli:
      image: wordpress:cli-php8.0
      volumes:
        - '.:/var/www/html:rw'
      links:
        - mariadb:mariadb
      depends_on:
        - mariadb
        - webserver
      command: "tail -f /dev/null"
